In [1]:
import numpy as np
A = np.array([[0, -2, 5], [1, 0, -6]])
B = np.array([[1,-1, 2], [2, 1, 5]])

In [2]:
A

array([[ 0, -2,  5],
       [ 1,  0, -6]])

In [3]:
B

array([[ 1, -1,  2],
       [ 2,  1,  5]])

In [4]:
A-B

array([[ -1,  -1,   3],
       [ -1,  -1, -11]])

In [5]:
A*B

array([[  0,   2,  10],
       [  2,   0, -30]])

In [6]:
np.dot(A.T, B)

array([[  2,   1,   5],
       [ -2,   2,  -4],
       [ -7, -11, -20]])